option1="1.Rule Managment"
option2="2.port Forwarding"
option3="3.Create network segment"
option4="4.See Avilable Interfaces "
option5="5.View Rules"
option6="6.save IPTables rules"
option7="7.Restart Iptables"
option8="8.Quit"
option9="9.Clear_screen"

ruleop1="1.Load old Rules"
ruleop2="2.Enter Rules manually"
ruleop3="3.Add ip Rules"
ruleop4="4.Add Service Rule"
ruleop5="5.Back"
