option1="1.Rule Managment"
option2="2.port Forwarding"
option3="3.Create network segment"
option4="4.See Avilable Interfaces "
option5="5.View Rules"
option6="6.delete Rules"
option7="7.Modify rules"
option8="8.save IPTables rules"
option9="9.Restart Iptables"
option10="10.Quit"
option11="11.Clear_screen"

ruleop1="1.Load old Rules"
ruleop2="2.Enter Rules manually"
ruleop3="3.Add ip Rules"
ruleop4="4.Add Service Rule"
ruleop5="5.Back"

delop1="1.Delete a rule By line"
delop2="2.Delete a rule By specifications"
delop3="3.Delete a rule manually(CUSTOM Rule) "
delop4="4.Back"
